// Portfolio content — work, projects, music
window.PORTFOLIO_DATA = {
  identity: {
    name: "Ezequiel Cutin",
    tagline: "Engineer, builder, occasional techno producer.",
    location: "Metro Detroit, MI",
    headshot: "headshot_budapest.png",
    bio: "Born in Miami, studied and currently living in Michigan. I write software for a living, make techno when I can, and watch way too much football — the real one, not American. Producing music has taught me more about engineering than most classes did: the patience, the iteration, the obsession with getting small details right. I like building things that feel good to use, and tinkering with things until they do.",
    bioShort: "I write software for a living and make techno when I can. Currently building developer tooling at UWM and trading systems at Glenbrook.",
    links: [
      { label: "GitHub",     href: "https://github.com/ezequielcutin",                  handle: "@ezequielcutin" },
      { label: "LinkedIn",   href: "https://www.linkedin.com/in/ezequiel-cutin/",       handle: "ezequiel-cutin" },
      { label: "X",          href: "https://x.com/ezecutin",                            handle: "@ezecutin" },
      { label: "SoundCloud", href: "https://soundcloud.com/ezequiel-cutin-187993918",   handle: "ezequiel-cutin" },
      { label: "Email",      href: "mailto:hello@ezequielcutin.com",                    handle: "hello@ezequielcutin.com" },
    ],
  },

  now: [
    { role: "Software Developer I", at: "United Wholesale Mortgage", entry: "uwm" },
    { role: "Algorithm Developer",  at: "Glenbrook Trading",         entry: "glenbrook" },
  ],

  work: [
    {
      id: "uwm",
      title: "Software Developer I",
      org: "United Wholesale Mortgage",
      date: "Jan 2025 — Present",
      location: "Metro Detroit, MI",
      current: true,
      bullets: [
        "Troubleshoot and maintain Bolt, UWM's cutting-edge AI platform for mortgage workflows, ensuring stability through data extraction and automation.",
        "Develop and run unit/integration tests to ensure seamless performance across the frontend and backend microservices.",
        "Support CI/CD pipelines, contributing to fast, reliable deployments with minimal disruption.",
        "Serve on Bolt's developer council, defining and enforcing code standards and quality benchmarks across the product.",
      ],
      stack: ["React", "JavaScript", "C#", ".NET Core", "SQL", "Azure", "Apache Kafka", "Docker", "CI/CD"],
    },
    {
      id: "glenbrook",
      title: "Algorithm Developer",
      org: "Glenbrook Trading",
      date: "Jun 2024 — Present",
      location: "Remote",
      current: true,
      bullets: [
        "Architected the entire quant engine end-to-end — from cloud storage and data pipelines to model serving and live monitoring.",
        "Built cloud infrastructure on AWS S3 for backtesting and optimizing trading models.",
        "Developed full-stack tooling (React, C#, Python) to monitor live model performance.",
        "Dockerized and packaged the quant engine for consistent team-wide development.",
        "Designed and trained LSTM and decision tree models for predictive market analytics.",
      ],
      stack: ["Python", "C#", "React", "TensorFlow", "PyTorch", "AWS", "Docker", "Pandas", "Plotly", "Cloud Architecture", "Distributed Systems", "WebSockets"],
    },
    {
      id: "zoox",
      title: "Automated Driver / Software Operator",
      org: "Zoox",
      date: "Oct 2024 — Jan 2025",
      location: "Miami, FL",
      bullets: [
        "Ran autonomous-driving test operations in downtown Miami, validating behavior in complex urban traffic.",
        "Logged and reviewed telemetry to spot deviations and prioritize fixes.",
        "Coordinated with engineers to capture edge cases and improve test coverage.",
      ],
      stack: ["Autonomous Systems", "Software Testing", "Telemetry", "QA"],
    },
    {
      id: "umich-ta",
      title: "Teaching Assistant",
      org: "University of Michigan",
      date: "Aug 2023 — May 2024",
      location: "Ann Arbor, MI",
      bullets: [
        "Supported undergrad and graduate courses in entrepreneurial B2B sales and innovation.",
        "Acted as investor for student projects, evaluating proposals and giving feedback.",
        "Coached on sales strategy, IP, and investment acquisition.",
      ],
      stack: ["Mentoring", "B2B Sales", "Pedagogy", "Evaluation"],
    },
    {
      id: "msh",
      title: "Technical Product Management Intern",
      org: "MSH",
      date: "Jun 2023 — Aug 2023",
      location: "Ft. Lauderdale, FL",
      bullets: [
        "Supported an AI-assisted hiring workflow inside a SaaS product, generating structured interview prompts.",
        "Ran beta user interviews and contributed to scrum + UX collaboration.",
        "Built automated checks with testim.io, including CAPTCHA validation flows.",
      ],
      stack: ["Product Management", "Scrum", "Test Automation", "GenAI", "React"],
    },
    {
      id: "eia",
      title: "Technical Lead",
      org: "European Innovation Academy",
      date: "Jul 2022 — Aug 2022",
      location: "Porto, Portugal",
      bullets: [
        "3-week startup accelerator: co-founded Ugly Buckets — fashion meets personal safety — with a team of 5.",
        "Owned all technical work: responsive site, 3D product prototypes, e-commerce backend.",
        "Pitched the final product to a panel of investors.",
      ],
      stack: ["Entrepreneurship", "3D Modeling", "Pitching", "Scrum"],
      images: [
        { src: "uglybuckets.png",  alt: "Ugly Buckets brand" },
        { src: "3dmodel.png",      alt: "3D product model" },
        { src: "3dmodel1.png",     alt: "3D product model — alt view" },
      ],
    },
    {
      id: "detroit",
      title: "Data Analyst",
      org: "City of Detroit",
      date: "May 2022 — Jul 2022",
      location: "Detroit, MI",
      bullets: [
        "Validated housing imagery against Detroit's Census criteria for habitable residences.",
        "Used geospatial analysis and ML to assess housing condition and predict habitability.",
        "Wrote reports and visualizations to inform city policy and fund allocation.",
      ],
      stack: ["Python", "SQL", "GIS", "Machine Learning", "Excel"],
    },
  ],

  projects: [
    {
      id: "quietly",
      title: "Quietly Build",
      tagline: "Ritual-based productivity PWA for founders",
      date: "Feb 2026 — Present",
      blurb: "Mobile-first productivity app built around daily rituals — morning intentions, timed focus sessions, evening reflections — instead of task lists. Ambient co-working presence, procedural audio, and a force-directed idea graph.",
      bullets: [
        "Morning/evening rituals with streak tracking and voice memo capture.",
        "Procedural Web Audio engine: brown noise, binaural beats, breath-synced entrainment.",
        "Force-directed idea graph (D3.js) with bidirectional linking and mobile physics.",
        "Real-time co-working presence via PartyKit WebSockets.",
        "Offline-capable PWA with Workbox service worker.",
      ],
      stack: ["Next.js", "TypeScript", "Tailwind", "Framer Motion", "Supabase", "Postgres", "PartyKit", "D3.js", "Web Audio"],
      links: [{ label: "Live", href: "https://quietly.build" }],
    },
    {
      id: "job-tracker",
      title: "Job Application Tracker",
      tagline: "Full-stack web app",
      date: "Sep 2024 — Oct 2024",
      blurb: "Helps job seekers manage applications with analytics, geocoded maps, and bulk import. JWT auth, real-time updates, and full CRUD.",
      bullets: [
        "Node.js + Express backend with PostgreSQL.",
        "React + Redux frontend with real-time updates.",
        "Chart.js analytics + Mapbox geocoding.",
        "CSV/XLSX bulk import and email password reset.",
      ],
      stack: ["Node.js", "Express", "Postgres", "React", "TypeScript", "Redux", "Mapbox", "Chart.js"],
      links: [
        { label: "GitHub",    href: "https://github.com/ezequielcutin/job-application-tracker" },
        { label: "Live Demo", href: "https://job-application-tracker-nu.vercel.app/" },
      ],
    },
    {
      id: "gobank",
      title: "GoBank",
      tagline: "Full-stack banking simulator",
      date: "Aug 2024 — Sep 2024",
      blurb: "Banking app simulating real financial operations: secure auth, transfers, transaction history, and a Monopoly Bank account for testing scenarios.",
      bullets: [
        "Go backend with PostgreSQL and JWT authentication.",
        "React + TypeScript frontend with Tailwind and Chart.js.",
        "Real-time balance updates and overdraft protection.",
      ],
      stack: ["Go", "Postgres", "JWT", "React", "TypeScript", "Tailwind", "Docker"],
      links: [{ label: "GitHub", href: "https://github.com/ezequielcutin/gobank" }],
    },
    {
      id: "spotify",
      title: "Spotify Track Downloader",
      tagline: "API integration with metadata enrichment",
      date: "Aug 2024 — Sep 2024",
      blurb: "Downloads Spotify tracks as MP3s with full metadata. Combines Spotify Web API for track info with YouTube Data API for full-length audio.",
      bullets: [
        "OAuth 2.0 against the Spotify Web API.",
        "YouTube Data API for full-length retrieval.",
        "Mutagen-based metadata enrichment with embedded album art.",
      ],
      stack: ["Python", "Flask", "Spotipy", "yt-dlp", "Mutagen"],
      video: "spotify-to-mp3-demo-video.mp4",
      links: [{ label: "GitHub", href: "https://github.com/ezequielcutin/spotify-to-mp3" }],
      note: "Educational only — not deployed publicly.",
    },
    {
      id: "fractal",
      title: "Fractal Mountain Generator",
      tagline: "WebGL + linear algebra",
      date: "Aug 2024",
      blurb: "Recursive fractal mountain landscapes built with WebGL. A small study in vector ops, geometric transformations, and recursive geometry.",
      stack: ["JavaScript", "WebGL"],
      images: [
        { src: "fractal-mountain.png",        alt: "Fractal mountain render" },
        { src: "fractal-mountain-inputs.png", alt: "Generator inputs panel" },
      ],
      links: [
        { label: "GitHub", href: "https://github.com/ezequielcutin/fractal-mountain" },
        { label: "Live",   href: "https://ezequielcutin.github.io/fractal-mountain/" },
      ],
    },
    {
      id: "tickets",
      title: "Customer Support Microservice",
      tagline: "Auth, RBAC, real-time notifications",
      date: "Jun 2024 — Jul 2024",
      blurb: "Scalable Node.js microservice for support tickets — JWT auth, role-based access control, WebSocket notifications, and Swagger-documented API.",
      stack: ["Node.js", "Express", "MongoDB", "JWT", "WebSockets", "Swagger", "Jest"],
      images: [{ src: "api-endpoint.png", alt: "Swagger API documentation" }],
      links: [
        { label: "API Docs", href: "https://rayca-eval-live-deae50ac2c84.herokuapp.com/api-docs" },
        { label: "GitHub",   href: "https://github.com/ezequielcutin/rayca-eval" },
      ],
    },
    {
      id: "wiki-search",
      title: "Wikipedia Search Engine",
      tagline: "EECS 485 · TF-IDF + PageRank",
      date: "Apr 2024 — May 2024",
      blurb: "Document retrieval engine using Hadoop MapReduce, TF-IDF scoring, and PageRank — deployed on AWS for scale.",
      stack: ["React", "Hadoop", "AWS", "TF-IDF", "PageRank"],
      images: [{ src: "ask485.png", alt: "ask485 search interface" }],
      links: [{ label: "GitHub (private)", href: "https://github.com/ezequielcutin/wikipedia-search-engine" }],
      note: "Private per UMich honor code.",
    },
    {
      id: "mapreduce",
      title: "Custom MapReduce Server",
      tagline: "EECS 485 · distributed systems",
      date: "Mar 2024 — Apr 2024",
      blurb: "Fully functional MapReduce server in Python — TCP/UDP networking, multithreading, master/worker architecture, and fault tolerance.",
      stack: ["Python", "TCP/UDP", "WebSockets", "Multithreading"],
      links: [{ label: "GitHub (private)", href: "https://github.com/abtaylor02/p4-mapreduce" }],
      note: "Private per UMich honor code.",
    },
  ],

  music: {
    intro: "Techno, house, and ambient — produced under my own name. Iteration and patience translate well to engineering.",
    soundcloud: "https://soundcloud.com/ezequiel-cutin-187993918",
    // Real titles/artwork are pulled from SoundCloud's oEmbed on mount.
    // The strings below are best-guess fallbacks shown only until oEmbed resolves.
    tracks: [
      { url: "https://soundcloud.com/ezequiel-cutin-187993918/hardcore-mf",          title: "Hardcore MF",         kind: "Techno"  },
      { url: "https://soundcloud.com/ezequiel-cutin-187993918/solace",               title: "Solace",              kind: "Ambient" },
      { url: "https://soundcloud.com/ezequiel-cutin-187993918/alien-transmissions",  title: "Alien Transmissions", kind: "Techno"  },
      { url: "https://api.soundcloud.com/tracks/1867505247", title: "—", kind: "—" },
      { url: "https://api.soundcloud.com/tracks/1844941479", title: "—", kind: "—" },
      { url: "https://api.soundcloud.com/tracks/1838947944", title: "—", kind: "—" },
      { url: "https://api.soundcloud.com/tracks/1254042886", title: "—", kind: "—" },
    ],
  },
};
