#!/usr/bin/env node
// Builds app.bundle.js from the JSX sources.
//
// The .jsx files are classic scripts, not modules — no imports, no exports,
// relying on globals and cross-file hoisting. So this transforms each file's
// JSX and concatenates them in load order rather than bundling a module
// graph. Their 47 top-level names do not collide, which is what makes
// sharing one scope safe; layouts.jsx already aliases its hooks to
// useStateL/useEffectL for exactly this reason.
//
// Usage: node scripts/build.mjs [--watch]

import { build as esbuild, transform } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { watch } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

// Load order matters: icons defines window.PFIcons, components consumes it,
// layouts consumes components, app mounts. components.jsx:2 destructures
// hooks off React, so the vendor prelude has to come first.
const SOURCES = ["icons.jsx", "components.jsx", "layouts.jsx", "app.jsx"];
const OUT = "app.bundle.js";

// react-dom/client provides createRoot; react-dom provides createPortal and
// flushSync. All three are used, so both entry points are merged onto the
// single ReactDOM global the sources expect.
const VENDOR_ENTRY = `
import * as React from "react";
import * as ReactDOM from "react-dom";
import { createRoot, hydrateRoot } from "react-dom/client";
globalThis.React = React;
globalThis.ReactDOM = { ...ReactDOM, createRoot, hydrateRoot };
`;

async function buildVendor() {
  const result = await esbuild({
    stdin: { contents: VENDOR_ENTRY, resolveDir: ROOT, loader: "js" },
    bundle: true,
    write: false,
    format: "iife",
    minify: true,
    target: ["es2019"],
    define: { "process.env.NODE_ENV": '"production"' },
  });
  return result.outputFiles[0].text;
}

async function transformSources() {
  const parts = [];
  for (const file of SOURCES) {
    const source = await readFile(join(ROOT, file), "utf8");
    const { code } = await transform(source, {
      loader: "jsx",
      target: "es2019",
      minify: true,
      sourcefile: file,
    });
    parts.push(`/* ${file} */\n${code}`);
  }
  return parts.join("\n");
}

// The bundle is a classic script, not a module: top-level declarations have
// to stay in the shared global scope, so this deliberately does NOT wrap the
// app code in an IIFE. Only the vendor prelude is self-contained.
async function buildBundle() {
  const [vendor, app] = await Promise.all([buildVendor(), transformSources()]);
  const banner = "/* Generated by scripts/build.mjs — do not edit. */\n";
  const code = `${banner}${vendor}\n${app}`;
  await writeFile(join(ROOT, OUT), code, "utf8");

  const hash = createHash("sha256").update(code).digest("hex").slice(0, 8);
  await injectHash(hash);

  return { bytes: Buffer.byteLength(code), hash };
}

// Replaces the manual ?v= bumping that has repeatedly served stale code.
async function injectHash(hash) {
  const path = join(ROOT, "index.html");
  const html = await readFile(path, "utf8");
  const next = html.replace(
    /(<script src=")app\.bundle\.js(?:\?v=[^"]*)?(">)/,
    `$1${OUT}?v=${hash}$2`
  );
  if (next !== html) await writeFile(path, next, "utf8");
}

const isWatch = process.argv.includes("--watch");

const run = async () => {
  const started = Date.now();
  try {
    const { bytes, hash } = await buildBundle();
    console.log(
      `built ${OUT} — ${(bytes / 1024).toFixed(1)} KB, v=${hash}, ${Date.now() - started}ms`
    );
  } catch (err) {
    console.error("build failed:", err.message);
    if (!isWatch) process.exitCode = 1;
  }
};

await run();

if (isWatch) {
  console.log("watching JSX sources…");
  let timer = null;
  for (const file of SOURCES) {
    watch(join(ROOT, file), () => {
      clearTimeout(timer); // editors fire several events per save
      timer = setTimeout(run, 60);
    });
  }
}
